### ISSUE TITLE
Package Failure

### ISSUE THREAD

**Issue by wilsonge** [photodude/coding-standards#14] opened 2017-02-15 01:35 UTC
This looks like the last of the unit test issues. 

This is 'expected' given our current rule that in a file sniff we require a package tag https://github.com/photodude/coding-standards/blob/patch-2/Joomla/Sniffs/Commenting/FileCommentSniff.php#L40-L44

**Comment by photodude** [comment] 2017-02-16 18:39
The sniff should function so as to only require the package tag if the file has not been namespaced. 

See https://github.com/joomla/coding-standards/blob/phpcs-2/Joomla/Sniffs/Commenting/FileCommentSniff.php#L268-L281

**Comment by photodude** [comment] 2017-02-16 18:43
The other "errors" reported with the package tag were due to a couple of coding issues where the class and file tags were getting mixed up, but that was resolved in one of the recent PRs.

I'm going to close this issue as expected behavior, CS fixes were applied resolving the package tag location in the code standard, and the fixes to the reporting of the tags.

**Closed as completed by photodude** 2017-02-16 18:43 UTC
