### ISSUE TITLE
InstantiateNewClasses - null and short array usage is valid too

### ISSUE THREAD

**Issue by vess** [photodude/coding-standards#9] opened 2015-09-25 02:26 UTC
Following https://github.com/photodude/coding-standards/pull/8 T_NULL and T_OPEN_SHORT_ARRAY should be added as well, since
`new Class([]);` and `new Class(null);` will fail.

Also the if/else in the do-while probably is not necessary.

Add some more lines to the test to reach 100% coverage.

Testing all these things here https://github.com/yaapi/coding-standards at the moment.

**Comment by photodude** [comment] 2015-12-15 20:20
Short Array tags fail by design, once PHP 5.3 support is eliminated from Joomla we can support short array tags.
(it is noted that some Joomla projects already ended support for PHP 5.3, those projects will need to override this area until PHP 5.3 support has ended)

**Comment by photodude** [comment] 2016-03-20 23:27
I have added T_NULL as suggested. Leaving T_OPEN_SHORT_ARRAY out of the cases until PHP5.3 support has been eliminated from the supported versions

Closing with https://github.com/photodude/coding-standards/commit/346d58596b44ed0c42c72f45ca83f9c8ebd73bde

**Closed as completed by photodude** 2016-03-20 23:27 UTC
